### ISSUE TITLE
'count' command not supported

### ISSUE THREAD

**Issue by noca** [bitly/asyncmongo#5]
I'm using aysncmongo on my project, and it works cool. Thanks for you   brilliant work!

And now I'm encounter a problem on using the command 'count', and a little cofused. 
I have a requirement for getting the count of a query, and I coded it like:

db['$cmd'].find_one({'count' : 'mycollect'}, call_back=resp_func)

But it didn't work.....
I then noticed that there is a '_is_command' parameter for 'find()'. I also noticed that in fact it is not in use, but instead passed 'False' directly to the 'self.__is_command', which will be used for creating the 'find_spec'. 
I hacked the code to use '_is_command' parameter, and the code is:

db['$cmd'].find_one({'count' : 'mycollect'}, _is_command=True, call_back=resp_func)

And it works!

I think there must be some reason for disable the '_is_command' option, and I wonder why? ^_^ And also is it safe for just use the 'count' command? 

Thanks a lot for the work!!

**Comment by sirpengi** [comment]
Note: this only applies to the latest git version (the latest stable from pypi doesn't have this yet).

The new version in git (since https://github.com/bitly/asyncmongo/commit/5e502104a13ef1fb56c0699c0eba194cf6c4764c ) does allow you to pass _is_command argument there.

I also had this issue and needed to run distincts and counts.  I'm using the new Client.command function though (you could continue doing it your way using db['$cmd'] or use what I've got):

``` python
command = {
  'distinct': 'collectionname',
  'key': 'distinctkey',
  'query': query_spec,
}
self.db.command(command, callback=callback)
```

and

``` python
command = {
  'count': 'collectionname',
  'query': query_spec,
}
self.db.command(command, callback=callback)
```

It'd be nifty if stub helpers were attached to the Cursor class so that everything is available there (so we do cursor.save(), cursor.update(), cursor.distinct(), cursor.count() etc.)

**Comment by pascalc** [comment]
I'm using the latest git version of asyncmongo (0.1.3) and I'm having issues with using the new db.command syntax. 

When I try

```
command = SON()
command['findandmodify'] = 'seq'
command['query'] = { '_id' : "myids" }
command['update'] = { '$inc': { 'seq': long(1) } }
command['new'] = True
command['upsert'] = True
db.command(command, callback=callback)
```

I get a TypeError saying: 'Cursor' object is not callable.

But if I do 

```
command = SON()
command['findandmodify'] = 'seq'
command['query'] = { '_id' : "myids" }
command['update'] = { '$inc': { 'seq': long(1) } }
command['new'] = True
command['upsert'] = True
db["$cmd"].find_one(command, _is_command=True, callback=callback)
```

It works out fine. Any ideas about what's going wrong?
